using System.Text.RegularExpressions;

namespace PrReviewBot.Services;

// Decides which changed files are worth a reviewer's attention, and in which
// order they are worth it when the PR has more files than the review limit.
//
// This replaced an allow-list of extensions, which failed in both directions:
// it let through lockfiles and generated code (package-lock.json matched
// ".json"), and it silently dropped real code it had not heard of (.sql, .ps1,
// .props, .cshtml, Dockerfile, ...). Worse, the file limit was applied in the
// order Azure DevOps listed the files, so a lockfile early in the list could
// push real source out of the review. Now everything textual is reviewable
// unless it is known noise, and the limit keeps the most important files.
internal static class FileClassifier
{
    private static readonly HashSet<string> BinaryExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".webp", ".tif", ".tiff", ".svg",
        ".pdf", ".zip", ".gz", ".tgz", ".7z", ".rar", ".tar",
        ".dll", ".exe", ".pdb", ".so", ".dylib", ".nupkg", ".snupkg", ".jar", ".class",
        ".woff", ".woff2", ".ttf", ".otf", ".eot",
        ".mp3", ".mp4", ".wav", ".mov", ".avi", ".webm",
        ".snk", ".pfx", ".p12", ".cer", ".keystore",
        ".xlsx", ".xls", ".docx", ".doc", ".pptx"
    };

    private static readonly HashSet<string> LockFileNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml", "bun.lockb",
        "packages.lock.json", "paket.lock", "Cargo.lock", "poetry.lock", "Pipfile.lock",
        "composer.lock", "Gemfile.lock", "go.sum"
    };

    private static readonly string[] GeneratedSuffixes =
    [
        ".designer.cs", ".g.cs", ".g.i.cs", ".generated.cs", ".generated.ts", ".generated.js",
        ".min.js", ".min.css", ".js.map", ".css.map", ".map", "modelsnapshot.cs"
    ];

    private static readonly string[] VendoredSegments =
        ["/node_modules/", "/obj/", "/dist/", "/wwwroot/lib/", "/.vs/"];

    private static readonly HashSet<string> DocExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".md", ".txt", ".rst", ".adoc"
    };

    private static readonly HashSet<string> StyleExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".css", ".scss", ".sass", ".less"
    };

    private static readonly HashSet<string> ConfigExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".json", ".yaml", ".yml", ".xml", ".config", ".csproj", ".esproj", ".fsproj", ".vbproj",
        ".props", ".targets", ".sln", ".slnx", ".toml", ".ini", ".env", ".editorconfig",
        ".bicep", ".tf", ".tfvars", ".resx"
    };

    private static readonly HashSet<string> ConfigFileNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "Dockerfile", ".dockerignore", ".gitignore", ".gitattributes", ".editorconfig", "Makefile"
    };

    // Why a file is not reviewed, or null when it is.
    public static string? ExclusionReason(string path, IReadOnlyList<string> extraExcludedGlobs)
    {
        string normalized = Normalize(path);
        string name = FileName(normalized);
        string extension = Path.GetExtension(name);

        if (BinaryExtensions.Contains(extension))
        {
            return "binary or media file";
        }

        if (LockFileNames.Contains(name))
        {
            return "lockfile (generated by the package manager)";
        }

        if (GeneratedSuffixes.Any(s => name.EndsWith(s, StringComparison.OrdinalIgnoreCase)))
        {
            return "generated or minified file";
        }

        if (VendoredSegments.Any(s => normalized.Contains(s, StringComparison.OrdinalIgnoreCase)))
        {
            return "build output or vendored dependency";
        }

        if (extraExcludedGlobs.Any(g => GlobMatches(g, normalized)))
        {
            return "excluded by Review:ExcludedPaths";
        }

        return null;
    }

    // Lower is more important. When a PR has more files than the review limit,
    // the files kept are the most important ones.
    public static FilePriority Priority(string path)
    {
        string normalized = Normalize(path);
        string name = FileName(normalized);
        string extension = Path.GetExtension(name);

        if (IsTest(normalized, name))
        {
            return FilePriority.Test;
        }

        if (DocExtensions.Contains(extension))
        {
            return FilePriority.Documentation;
        }

        if (StyleExtensions.Contains(extension))
        {
            return FilePriority.Style;
        }

        if (ConfigExtensions.Contains(extension) || ConfigFileNames.Contains(name))
        {
            return FilePriority.Configuration;
        }

        return FilePriority.Source;
    }

    // Stable: files of equal priority keep the order they came in.
    public static List<T> RankByPriority<T>(IEnumerable<T> items, Func<T, string> pathOf)
        => [.. items.OrderBy(i => Priority(pathOf(i)))];

    private static bool IsTest(string normalized, string name)
    {
        if (normalized.Contains("/test/", StringComparison.OrdinalIgnoreCase)
            || normalized.Contains("/tests/", StringComparison.OrdinalIgnoreCase)
            || normalized.Contains("/__tests__/", StringComparison.OrdinalIgnoreCase)
            || normalized.Contains(".tests/", StringComparison.OrdinalIgnoreCase)
            || normalized.Contains(".test/", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        string stem = Path.GetFileNameWithoutExtension(name);
        return stem.EndsWith("Tests", StringComparison.Ordinal)
            || stem.EndsWith("Test", StringComparison.Ordinal)
            || stem.EndsWith(".test", StringComparison.OrdinalIgnoreCase)
            || stem.EndsWith(".spec", StringComparison.OrdinalIgnoreCase);
    }

    // A small glob: `**` matches across folders, `*` within one, `?` one
    // character. Patterns without a leading slash match at any depth.
    internal static bool GlobMatches(string glob, string path)
    {
        string pattern = glob.Replace('\\', '/').Trim();
        if (pattern.Length == 0)
        {
            return false;
        }

        if (!pattern.StartsWith('/'))
        {
            pattern = "**/" + pattern;
        }

        string regex = "^" + Regex.Escape(pattern)
            .Replace(@"\*\*/", "(?:.*/)?", StringComparison.Ordinal)
            .Replace(@"\*\*", ".*", StringComparison.Ordinal)
            .Replace(@"\*", "[^/]*", StringComparison.Ordinal)
            .Replace(@"\?", "[^/]", StringComparison.Ordinal) + "$";

        return Regex.IsMatch(Normalize(path), regex, RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
    }

    private static string Normalize(string path)
    {
        string p = path.Replace('\\', '/');
        return p.StartsWith('/') ? p : "/" + p;
    }

    private static string FileName(string normalized) => normalized[(normalized.LastIndexOf('/') + 1)..];
}

internal enum FilePriority
{
    Source = 0,
    Configuration = 1,
    Test = 2,
    Style = 3,
    Documentation = 4
}
